# Generated by Django 5.2.7 on 2026-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pin_code',
            field=models.CharField(blank=True, help_text='4-digit quick login PIN', max_length=4),
        ),
    ]
